Solution of exercise tree related to DB.Develop
crisgahur/Kiadealership pull request #1
Opened 2023-03-02 22:29 UTC by crisgahur

Uploading exercise of ticket [BACK-33](https://vulky.atlassian.net/browse/DB-33).

This is a Data Base exercise developed in MySQL Workbench 8.0.29. In this project you will find these concepts applied:

- Store Procedures.
- UML
- Attributes
- Encapsulation

2023-03-13 17:39 UTC, MauroCaro commented on sp_show_sell_employee1.sql
> +SELECT * FROM SELL WHERE id_employee=1
You must receive a param with the employee ID, otherwise every tie I call sp_show_sells_employee1 will bring the employee 1 wich is incorrect

2023-03-13 17:42 UTC, MauroCaro commented on Kiadealership.sql
> +CALL sp_show_sells_employee1();
You have to include the store procedure creation on this script, the reason why is when executing this line, it will throw an error due I need to orderly exceute, first the store procedures and this script, so please include the store procedures creations before calling those

2023-03-13 17:42 UTC, MauroDecodificado requested changes
Check comments

2023-03-14 13:56 UTC, crisgahur commented on Kiadealership.sql
> +CALL sp_show_sells_employee1();
You're right. Corrected.

2023-03-14 13:57 UTC, crisgahur commented on sp_show_sell_employee1.sql
> +SELECT * FROM SELL WHERE id_employee=1
You're right. Corrected.

2023-03-14 17:50 UTC, MauroCaro requested changes
You delete the sotres procedures, but you did not add them to the main script, and still calling for them even when they do not exist, so please check

2023-03-16 17:54 UTC, MauroCaro approved these changes
Approved and can be merged

2023-03-17 14:21 UTC, merged